### ISSUE TITLE
Replace twtr contact info w/ nostr npub

### ISSUE THREAD

**Issue by alltheseas** [PlebeianTech/plebeian-market#207]
Pleb market states "_`Plebeian Market is a distributed self sovereign P2P market place.`_", while requiring a twitter handle.

Can you enable a nostr/npub option in addition to, or instead of a twtr handle?

**Comment by chiefmonky** [comment]
Yes regarding the Twitter ID, we do not use their login api... we send 3 words from the BIP39 list, if you confirm those you get access 

The nostr login is coming imminently

**Comment by ralyodio** [comment]
is this project dead?

**Comment by ibz** [comment]
Very much alive, perhaps more than ever!

But we're still working hard to finish the new version, which is fully built on Nostr, so we didn't have much time to update the old version, still in production, with simple fixes that should have been there ages ago.

We're getting very close!

**Comment by ralyodio** [comment]
oh where's the repo for the new version?

**Comment by ralyodio** [comment]
I’d the full stack sported on docker yet?- Anthony(408) 656-2473 On Oct 2, 2023, at 6:54 AM, Ioan Bizău ***@***.***> wrote:﻿
Same repo, you can see we are committing a lot of stuff to the master branch. The "prod" branch is pretty much dead, except for critical fixes.

**Comment by ralyodio** [comment]
are there docs for running the new version in docker fully self-hosted?

**Comment by ibz** [comment]
See README. But it's not great, because we've been adding more components and more steps that are not fully documented.

But basically:

* `./scripts/dev.sh` / `./scripts/prod.sh` ... these run the dockerized components of the backend (DB, API & Nostr communications layer)
* `npm i && npm run dev` under `web/frontoffice` runs the app buyers use to browse stalls and buy products - this talks to Nostr relays only, not to our backend!
* `npm i && npm run dev` under `web/backoffice` runs the admin app, that you use to create products, manage orders, etc ... as a seller

But there are probably a couple more steps like config files, etc that need to be taken care of for the apps to work...

You can also play with our staging environment at https://staging.plebeian.market - which runs off master.

**Comment by ibz** [comment]
Nostr version is now up and running at https://plebeian.market!
